/* Game area */
const playGameButton = document.getElementById("play-game-button");
const playerName = document.getElementById("player-name");
const questionNumber = document.getElementById("question-number");
const question = document.getElementById("question");
const nextButton = document.getElementById("next-button");
const resultTextArea = document.getElementById("result-text-area");
const answer = document.getElementById("answer-input");
const saveResultButton = document.getElementById("save-result-button");
/* Form and player list dom */
const myForm = document.getElementById("my-form");
const name = document.getElementById("name");
const surname = document.getElementById("surname");
const playerList = document.getElementById("player-list");
const addPlayer = document.getElementById("add-player");
/* audio tag */
let mySong = document.getElementById("mySong");
let pauseButton = document.getElementById("pause");
let playButton = document.getElementById("play");
